### PR TITLE
Added a dependent style - SoftwareX.

### PR DESCRIPTION
**Pull request by StuntsPT**
This is related to [#1644 in the repository "styles"](https://github.com/citation-style-language/styles/pull/1644).
I suppose this should fix it.

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle --  how do we want to proceed with styles that aren't on Elsevier's list but are still dependents. For Springer we have an _extra.tab list. Do the same here?

@StuntsPT -- thanks, that table is auto-generated from an Excel file, though, so we probably don't want to add to it manually, but let's see what other folks think.

**Comment by StuntsPT** [comment]
@adam3smith -- So... you have an Excel file, that generates table files that get parsed by a script to create dependent styles.
However, in this case, since the journal is not on Elsevier's list, it should be placed on a new file "_extra.tab", which does not yet exist for Elsevier's list, but should be created to keep in line with what has been done before.
Am I missing anything? Just trying to understand the process so I can contribute more effectively. I rely heavily on Zotero, I'd like to give something back to the community too.

**Comment by adam3smith** [comment]
that's exactly right, we get the Excel right from Elsevier. Hold off on the _extra.tab file until we hear from @rmzelle, though, I want to make sure we agree that that's the way to go.
Thanks!

**Comment by rmzelle** [comment]
> it should be placed on a new file "_extra.tab", which does not yet exist for Elsevier's list, but should be created to keep in line with what has been done before.

Yes, exactly.

**Comment by adam3smith** [comment]
@StuntsPT OK, looks like we agree on this. If you want to go ahead and do that, that'd be great then.

**Comment by StuntsPT** [comment]
Ok, so I suppose this is the way it should be, right?
Thanks for showing me "the way". =-)

**Comment by adam3smith** [comment]
yes, thanks! If you want to, you can now run the .rb script locally and then copy the dependent style over--obviously we can take over at any point, but since you seem interested in the process I'll leave this to you until you tell us to.

**Comment by StuntsPT** [comment]
Thanks!

Should I also do the "cleanup"? (Using the --replace option seems to delete 8 dependent styles from the styles repository)

**Comment by adam3smith** [comment]
no, don't remove any styles. We'll check on all of these when we get the next iteration of the Elsevier list, which is, apparently a significant expansion (i.e. they cover more journals with their generic styles).

**Comment by StuntsPT** [comment]
Ok, so I'll just generate a new, dependent, style for "SoftwareX", and include it in my PR for the repository "styles".

**Comment by adam3smith** [comment]
yup

**Comment by StuntsPT** [comment]
Thanks, done!
For quick reference:
https://github.com/citation-style-language/styles/pull/1644

**Pull request merged**
