### PR TITLE
Initial commit for ASCE

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for doing this all by hand!

I looked around for some catalog data, but the best I found was http://ascelibrary.org/userimages/ContentEditor/1441123048214/2016SubscriptionCatalog_spread_web.pdf via http://ascelibrary.org/page/librarians, and that still would involve a lot of copy-and-pasting. There is third-party catalog data available via KB+/JISC, though, which is a good resource to be aware of: https://www.kbplus.ac.uk/demo/publicExport/index?offset=0&filter=&q=%22American+Society+of+Civil+Engineers%22&sort=sortname&order=asc&lastUpdated=&search=yes

**Comment by zuphilip** [comment]
Actually, the websites are quite homogenous and therefore to add 36 rows here were doable in less than 1 hour work. Thanks for the link. I normally prefer our journal services <a href="http://www.zeitschriftendatenbank.de/startseite/">ZDB</a> and <a href="http://ezb.uni-regensburg.de/">EZB</a>. They have also some nice lookup services, which I would like to explore further...

@rmzelle Did you notice that we reached 8.000+ CSL styles by now?!  :satisfied:

**Comment by rmzelle** [comment]
> @rmzelle Did you notice that we reached 8.000+ CSL styles by now?!  :satisfied:

I did! --> https://github.com/citation-style-language/styles/issues/1783#issuecomment-163700313

**Comment by rmzelle** [comment]
:tada: :balloon: :sparkles: :fireworks:

**Comment by zuphilip** [comment]
Yeah, maybe it is worth to post a notice on twitter?

**Comment by adam3smith** [comment]
On it on twitter.

**Pull request merged**
