### PR TITLE
Fix generation script

### PR DESCRIPTION
**Pull request by zuphilip**
This seems to be a regression from d6a642caae09d2786243562968a0f6c4911a5b4a

I followed the advices from http://www.dotnetperls.com/sub-ruby

### CODE REVIEW

**Comment by rmzelle** [comment]
Hmmmz, I'm pretty sure the old code worked in my testing.

Did you get unexpected results?

**Comment by rmzelle** [comment]
E.g. testing at http://rubular.com/ shows that `<updated>(.)+<\/updated>` matches "<updated>2015-10-25T09:01:49+00:00</updated>".

**Comment by zuphilip** [comment]
Yes, it was not replacing the Springer styles which were also generated before according to the Springer template, see my extra commit https://github.com/zuphilip/styles/commit/29b391e2c9a96a54070e995202a5cb2506981476

**Comment by rmzelle** [comment]
I'll trust you on that :). Your version is better anyway (it properly captures the date stamp as a match result, although I don't see why that should matter here).

**Comment by rmzelle** [comment]
Ah, I see now. The real bug was `str = str.gsub!()`. `gsub!` is meant for in place substitution, and doesn't (necessarily?) return the modified string (http://apidock.com/ruby/v1_9_3_392/String/gsub%21). `str = str.gsub()` or your `str.sub!()` should both do the trick.

**Comment by rmzelle** [comment]
I still swore the old code worked in my hands. Maybe I was testing it wrong. Good catch!

**Comment by zuphilip** [comment]
Yes, the regexp was just cosmetic. But the replacing options were making a different.
 * Replace in place: `value.sub!("at", "ote")`
 * Replace and assign: `newvalue = value.sub("ird", "ark")`

**Comment by rmzelle** [comment]
:fireworks:

**Comment by rmzelle** [comment]
I just discovered that `timestamp_regex = Regexp.new("/<updated>(.+)<\/updated>/")` should be `timestamp_regex = Regexp.new("<updated>(.+)<\/updated>")` (without the slashes). Current code doesn't work for me at all.

I broke this in https://github.com/citation-style-language/utilities/commit/f867079dc3a2cd7222907c28aa0b8f0d3d52e64a. Will fix.

http://ruby-doc.org/core-1.9.3/Regexp.html#method-c-new

**Pull request merged**
