### PR TITLE
Add International Journal of Pavement Engineering to _journal.tab

### PR DESCRIPTION
**Pull request by zuphilip**
... link it to the style taylor-and-francis-harvard-v as described in their manuscript guidelines.

I hope this update is in the correct form and at the correct place.

(See https://forums.zotero.org/discussion/40818/style-request-internationa-journal-of-pavement-engineering/#Item_2)

### CODE REVIEW

**Comment by rmzelle** [comment]
I just updated generate_styles_from_data.rb (https://github.com/citation-style-language/utilities/commit/c761d679248a8927ca5a4b53908a825d7d8a9318). I haven't test it very heavily, but it seems to work just fine.

You can now create an optional "_extra.tab" file. It requires the same header and column order as "_journals.tab". Skipping and renaming work just as before (e.g., a title that exist in "_journals.tab", "_extra.tab" and "_skip.txt" is still skipped; same for renaming with "_rename.tab").

The output shows the number of overwritten styles, e.g.:

```
Generating styles...
Generated 9			Overwrote 2	aacr
```

**Comment by adam3smith** [comment]
excellent, thanks!

On Mon, Jan 19, 2015 at 10:13 PM, Rintze M. Zelle <notifications@github.com>
wrote:

> I just updated generate_styles_from_data.rb (c761d67
> <https://github.com/citation-style-language/utilities/commit/c761d679248a8927ca5a4b53908a825d7d8a9318>).
> I haven't test it very heavily, but it seems to work just fine.
>
> You can now create an optional "_extra.tab" file. It requires the same
> header and column order as "_journals.tab". Skipping and renaming work just
> as before (e.g., a title that exist in "_journals.tab", "_extra.tab" and
> "_skip.txt" is still skipped; same for renaming with "_rename.tab").
>
> The output shows the number of overwritten styles, e.g.:
>
> Generating styles...
> Generated 9         Overwrote 2 aacr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/utilities/pull/14#issuecomment-70602125>
> .
>



-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by rmzelle** [comment]
The main remaining limitation I see is that the "--replace" flag currently only works in combination with "--directory". It would be nice to use "-r" by itself so we can quickly see if the "utilities" repo is in sync with the "styles" repo.

**Comment by rmzelle** [comment]
Also, this is getting off-topic, but we still have a bunch of Elsevier styles that once upon a time were generated, but which are absent from the current metadata set: https://gist.github.com/rmzelle/d6bb971948077a78cdc7. It looks like some but not all are on Carles's list.

**Comment by rmzelle** [comment]
The documentation at https://github.com/citation-style-language/utilities/blob/master/generate_dependent_styles/README.mdown is now up-to-date as well.

**Comment by rmzelle** [comment]
I added the "International Journal of Pavement Engineering " style in https://github.com/citation-style-language/utilities/commit/fb424bd94d730f2785819764da3dc7233245d9b2 and https://github.com/citation-style-language/styles/commit/04023dffa627aeb79570c2db7dd4d5b8059c1293 . I changed the parent to "taylor-and-francis-harvard-x", since that's the parent of "taylor-and-francis-harvard-v".

**Pull request closed without merging**
