### PR TITLE
Get rid of "data" subdirectory for input data

### PR DESCRIPTION
**Pull request by rmzelle**

### CODE REVIEW

**Comment by rmzelle** [comment]
Looks like we'll lose GitHub file history (see e.g. https://github.com/citation-style-language/utilities/commits/remove-data-subdir/generate_dependent_styles/aacr/_README.mdown). Local git clients (like SmartGit) are sometimes smart enough to pull up the history of moved files, so I'm not sure if this is such a big issue.

I have another move planned from "generate_dependent_styles" to root once we transfer all the journal metadata stuff over to a dedicated repo, but I would like to reorganize stuff as much as possible here before that move.

**Comment by rmzelle** [comment]
@adam3smith, @zuphilip, you don't mind if I go ahead and merge this?

The rest of my to do list:

* rename "generate_styles_from_data.rb" to just
"generate_styles.rb" (done)
* rename the "generated_styles" directory to something like "dependent" (which would match the "styles" repo) so that it's easier to autocomplete "generate_styles.rb" in the terminal/command line.
* put all the generated styles in a single folder,
instead of individual folders per dataset.
* leave the timestamp of existing generated styles alone if the rest of the style remains the same
* move all the stuff in "/generate_dependent_styles/" to its own repo at e.g. "citation-style-language/journal-metadata"
* change "" to something shorter like ''. The URL will be out-of-date after the move, and isn't really necessary.

**Comment by rmzelle** [comment]
Oh, and any existing pull request will break, but it looks like we don't have any :).

This is my last procrastination project before working on the next CSL release, by the way :P.

**Comment by zuphilip** [comment]
<b>A) File history</b>
<blockquote>Looks like we'll lose GitHub file history [...] Local git clients (like SmartGit) are sometimes smart enough to pull up the history of moved files</blockquote>
Yes, that depends on whether the `--follow` option is used, i.e. on the git bash:
```
$ git log --follow --format=oneline generate_dependent_styles/aacr/_README.mdown
29933dc5e2633ca70cc4c0a35a972c93791c1203 Get rid of "data" subdirectory for input data
e1a7b68fec734ee7ed2f95554311329ab98eb037 Small additional update AACR metadata
72c14b8140061d9eae5fff0d8a27586d8a72231a Remove space from journal title in the CSV file for the automatic generation of AACR styles.
```
<b>B) Renaming and Moving Files</b>
I don't care that much about the names of the file or the file structure. Thus, all points from your list above concering renaming or moving files are okay for me, as long as the utilities still work afterwards.

<b>C) New Repo for Dependent Style Generation</b>
<blockquote>move all the stuff in "/generate_dependent_styles/" to its own repo at e.g. "citation-style-language/journal-metadata"</blockquote>
That sounds like a larger change. Actually for me the `utilities` repo is mostly about generating dependent styles. I didn't use any of the other scripts at all. Is there any benefit from such a new repo?

<b>D) Output Directory</b>
I think it may make sense to have a (new?) option to indicate the output directory. I guess that first for some testing I would like to have a new test directory with just the new styles. But for the final generation I would like to choose the `dependent` directory of the `styles` repo.

<b>E) Pull Request</b>
Well, actually we have your work for the BMC https://github.com/citation-style-language/utilities/commit/b5297f086c780e7210f4c936e4e611eb04ae4a47 and https://github.com/citation-style-language/styles/pull/1570 but we decided to wait (I have not yet reached out to Springer).

**Comment by rmzelle** [comment]
> as long as the utilities still work afterwards.

That's certainly the goal, yes :).

> Actually for me the utilities repo is mostly about generating dependent styles. I didn't use any of the other scripts at all. Is there any benefit from such a new repo?

I think it might help us to get more publisher involvement if we make it as clear as possible as to how we generate our dependent styles. I don't like that we currently hide all this journal metadata three subdirectories deep in the utilities repo.

As for the rest of the files in the repo, it's a bit of a mess, but there are some important files there which I used to batch-edit, update files between CSL versions, and validate styles and locale files (https://github.com/citation-style-language/utilities/wiki has some descriptions on what's what).

> I think it may make sense to have a (new?) option to indicate the output directory.

Isn't that what the "--replace" option already does? Without it, styles are generated in a subdirectory of the "utilities" repo. With it, styles are also copied over to the "styles" repo (while deleting any old styles generated from the same data folder).

> Well, actually we have your work for the BMC

Ah, right. Can you reach out to Springer for a new list? Alternatively we could look at the new BMC metadata list (since http://old.biomedcentral.com/journals/biomedcentraljournallist.txt was recently updated).

**Comment by zuphilip** [comment]
<blockquote>I think it might help us to get more publisher involvement if we make it as clear as possible as to how we generate our dependent styles. I don't like that we currently hide all this journal metadata three subdirectories deep in the utilities repo.</blockquote>

That is a good goal to achieve. However, I don't think that it makes much a difference for the publishers when the information at github is more prominent. I would rather suggest to describe the procedure for non-programmers in a blog post and promote it through twitter etc. In the blog post one can mention several approaches by different publishers and trying to motivate further publishers to help the project.

**Comment by rmzelle** [comment]
Well, we already have http://citationstyles.org/publishers/.

**Comment by zuphilip** [comment]
Okay. Can you update the data in the table? It is 1,5 years old... Also a search option in the table would be nice (I think `data-table` already provides that feature).

[ I just googled "get involvement" and found <a href="http://www.theguardian.com/public-leaders-network/2011/jul/07/sevensteps-getting-communities-involved">this article from 2011</a>. Maybe that is interesting for you as well. ]

**Pull request merged**
