### PR TITLE
[Springer] Add Pflügers Archiv to extra list

### PR DESCRIPTION
**Pull request by zuphilip**
This fixes https://github.com/citation-style-language/styles/issues/1578
which was manually solved by
https://github.com/citation-style-language/styles/pull/1581

### CODE REVIEW

**Comment by zuphilip** [comment]
(
  Note, I can currently not run the Ruby script on my Springer folder, because an error occurs:
```
$ ruby generate_styles_from_data.rb -d springer
Script: C:/Users/zumstein/Coding/utilities/generate_dependent_styles
Input:  C:/Users/zumstein/Coding/utilities/generate_dependent_styles/data
Output: C:/Users/zumstein/Coding/utilities/generate_dependent_styles/generated_styles

Generating styles...
generate_styles_from_data.rb:21:in `gsub!': incompatible character encodings: CP850 and UTF-8 (Encoding::CompatibilityError)
        from generate_styles_from_data.rb:21:in `title_to_styleID'
        from generate_styles_from_data.rb:271:in `block (2 levels) in <main>'
        from generate_styles_from_data.rb:230:in `each'
        from generate_styles_from_data.rb:230:in `block in <main>'
        from generate_styles_from_data.rb:167:in `each'
        from generate_styles_from_data.rb:167:in `<main>'
```
)

**Comment by rmzelle** [comment]
Does it work without the changes from this PR?

**Comment by zuphilip** [comment]
No, it didn't work before and is not working afterwards. I think it is a character encoding problem. All my files should be encoded in UTF8. However, I don't know where the `CP850` is coming from...

**Comment by rmzelle** [comment]
Were you on Windows? Otherwise, you could try to run this on the Springer files: http://stackoverflow.com/questions/115210/utf-8-validation

**Comment by zuphilip** [comment]
Yep, I am on Windows.

**Comment by zuphilip** [comment]
Okay, I can produce the files with
```
 ruby --external-encoding UTF-8 generate_styles_from_data.rb -d springer
```
It works fine and creates 2022 styles and the new Pflüger style looks correctly.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
